DROP TABLE IF EXISTS ODONTOLOGOS; CREATE TABLE ODONTOLOGOS (ID INT AUTO_INCREMENT PRIMARY KEY, MATRICULA INT NOT NULL, NOMBRE VARCHAR(100), APELLIDO VARCHAR(80));

 -- para test --

 INSERT INTO ODONTOLOGOS (MATRICULA, NOMBRE, APELLIDO) VALUES (23456789, 'PEDRO', 'SUAREZ'), (4567899, 'CLARA', 'GOMEZ');